In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(666)
a = np.random.randint(1,100,100)

In [3]:
b = a.reshape(20,-1)

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
scaler = StandardScaler()

In [6]:
c = scaler.fit_transform(b)

D:\anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [7]:
scaler.inverse_transform(c)[:5]

array([[ 3., 46., 31., 63., 71.],
       [74., 31., 37., 62., 92.],
       [95., 52., 61., 96., 29.],
       [15., 98., 64., 17., 47.],
       [40., 70., 83., 77., 80.]])

In [8]:
scaler.fit_transform(b[:5])

D:\anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-1.22101504, -0.58280704, -1.27516865,  0.        ,  0.31557101],
       [ 0.8236092 , -1.23520298, -0.95901113, -0.03833698,  1.23598646],
       [ 1.42835722, -0.32184866,  0.30561893,  1.26512019, -1.52525988],
       [-0.87544475,  1.67883221,  0.46369769, -1.76350087, -0.73633236],
       [-0.15550663,  0.46102646,  1.46486316,  0.53671766,  0.71003477]])

In [9]:
b[:5]

array([[ 3, 46, 31, 63, 71],
       [74, 31, 37, 62, 92],
       [95, 52, 61, 96, 29],
       [15, 98, 64, 17, 47],
       [40, 70, 83, 77, 80]])

In [10]:
d = b[:5]

In [11]:
d[:,0]

array([ 3, 74, 95, 15, 40])

In [12]:
s = (d-d.mean(axis=0))/d.std(axis=0)

In [13]:
s

array([[-1.22101504, -0.58280704, -1.27516865,  0.        ,  0.31557101],
       [ 0.8236092 , -1.23520298, -0.95901113, -0.03833698,  1.23598646],
       [ 1.42835722, -0.32184866,  0.30561893,  1.26512019, -1.52525988],
       [-0.87544475,  1.67883221,  0.46369769, -1.76350087, -0.73633236],
       [-0.15550663,  0.46102646,  1.46486316,  0.53671766,  0.71003477]])

In [14]:
s*(d.std(axis=0))+(d.mean(axis=0))

array([[ 3., 46., 31., 63., 71.],
       [74., 31., 37., 62., 92.],
       [95., 52., 61., 96., 29.],
       [15., 98., 64., 17., 47.],
       [40., 70., 83., 77., 80.]])